# Set the version of Docker
version: "3.8"

# Define the services
services:
  nukelab:
    build: .
    image: nukelab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker socket
      - nukelab_data:/data

    ports:
      - "8000:8000" # Nukelab web server port
    networks:
      - nukelab # Set the network

volumes:
  nukelab_data:

# Define the networks
networks:
  nukelab:
    name: nukelab # Set the network
