# Copyright (c) NukeLab Development Team.
# Distributed under the terms of the Modified BSD License.

# Set the version of Docker
version: "3.8"

# Define the services
services:
  nukelab:
    build: .
    image: nukelab
    environment:
      - NUKELAB_ADMIN=${NUKELAB_ADMIN}
      - DOCKER_NUKELAB_IMAGE=${DOCKER_NUKELAB_IMAGE}
      - DOCKER_NUKELAB_DIR=${DOCKER_NUKELAB_DIR}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - OAUTH_CALLBACK_URL=${OAUTH_CALLBACK_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker socket
      - nukelab-data:/data

    ports:
      - "8000:8000" # Nukelab web server port
    networks:
      - nukelab-network # Set the network

volumes:
  nukelab-data:
    name: nukelab-data

# Define the networks
networks:
  nukelab-network:
    name: nukelab-network